### PR TITLE
fix issues with symfony options resolver

### LINKED ISSUE #262: Merge Request created_after not valid.
```
[Wed Oct  4 22:11:47 2017] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Gitlab\Api\MergeRequests::Gitlab\Api\{closure}() must implement interface DateTimeInterface, instance of Symfony\Component\OptionsResolver\OptionsResolver given, called in project/vendor/symfony/symfony/src/Symfony/Component/OptionsResolver/OptionsResolver.php on line 885 in project/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Api/MergeRequests.php:39
Stack trace:
#0 project/vendor/symfony/symfony/src/Symfony/Component/OptionsResolver/OptionsResolver.php(885): Gitlab\Api\MergeRequests->Gitlab\Api\{closure}(Object(Symfony\Component\OptionsResolver\OptionsResolver), Object(DateTime))
#1 project/vendor/symfony/symfony/src/Symfony/Component/OptionsResolver/OptionsResolver.php(716): Symfony\Component\OptionsResolver\OptionsResolver->offsetGet('created_a in project/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Api/MergeRequests.php on line 39
```

Apparenty setNOrmalizer i MegreRequest is throwing flatal error With Option Resolver.
Changing from:

`        $datetimeNormalizer = function (\DateTimeInterface $value) {
            return $value->format('c');
        };`
to:
`
        $datetimeNormalizer = function (Options $options, $value) {
            return $value->format('c');
        };` seems to fix the issue.

https://symfony.com/doc/current/components/options_resolver.html#option-normalization
Im using symfony3.3

### PR DESCRIPTION
**Pull request by m-bymike**
This fix also addresses issues with several boolean normalizers, that always normalized to true.

close #262

### CODE REVIEW

File: lib/Gitlab/Api/Groups.php [hunk 1]
```diff
@@ -18,7 +20,7 @@ class Groups extends AbstractApi
     public function all(array $parameters = [])
     {
         $resolver = $this->createOptionsResolver();
-        $booleanNormalizer = function ($value) {
+        $booleanNormalizer = function (OptionsResolver $resolver, $value) {
```
Comment (fbourigault) [inline lib/Gitlab/Api/Groups.php]: Could you typehint with `Symfony\Component\OptionsResolver\Options` instead?

Comment (m-bymike) [reply lib/Gitlab/Api/Groups.php]: Didn't realize there's an interface... done (see amended commit)

**Comment by fbourigault** [comment]
Thank you!
